/**
 * ====================================
 * LogHawk – Alert Model
 * ====================================
 * models/Alert.js
 * 
 * MongoDB schema for security alerts generated by the threat detection engine.
 * Alerts match user specifications for Phase 3.
 */

const mongoose = require('mongoose');

const alertSchema = new mongoose.Schema({
  // The analyst who owns this data
  user: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true,
  },
  // Type of Alert (e.g., "Brute Force Attack", "Suspicious IP Activity")
  alertType: {
    type: String,
    required: true,
  },
  // Severity: Title Case
  severity: {
    type: String,
    enum: ['Low', 'Medium', 'High', 'Critical'],
    required: true,
  },
  description: {
    type: String,
  },
  sourceIP: {
    type: String,
  },
  username: {
    type: String,
  },
  status: {
    type: String,
    enum: ['Open', 'Investigating', 'Resolved'],
    default: 'Open',
  },
  sourceFile: {
    type: String,
  },
  // AI Preparation placeholders
  riskScore: {
    type: Number,
    default: 0,
  },
  recommendedAction: {
    type: String,
  },
  // Linked raw log events for investigation & grouping
  relatedLogs: [{
    type: mongoose.Schema.Types.ObjectId,
    ref: 'ParsedLog',
  }],
  // Link to an incident if one has been created from this alert
  incidentId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Incident',
    default: null,
  },
}, {
  timestamps: true,
});

alertSchema.index({ user: 1, severity: 1 });
alertSchema.index({ status: 1 });
alertSchema.index({ sourceIP: 1 });

module.exports = mongoose.model('Alert', alertSchema);
